-- Seed achievements
INSERT INTO public.achievements (id, name, description, icon, category, xp_reward, requirement) VALUES
  ('first_game', 'First Steps', 'Complete your first game', '🎮', 'general', 50, '{"type": "games_played", "value": 1}'),
  ('games_10', 'Getting Started', 'Complete 10 games', '🏃', 'general', 100, '{"type": "games_played", "value": 10}'),
  ('games_50', 'Dedicated Player', 'Complete 50 games', '💪', 'general', 250, '{"type": "games_played", "value": 50}'),
  ('games_100', 'Globe Trotter', 'Complete 100 games', '🌍', 'general', 500, '{"type": "games_played", "value": 100}'),
  ('streak_3', 'Three-peat', 'Maintain a 3-day streak', '🔥', 'general', 75, '{"type": "streak", "value": 3}'),
  ('streak_7', 'Week Warrior', 'Maintain a 7-day streak', '⚡', 'general', 200, '{"type": "streak", "value": 7}'),
  ('streak_30', 'Monthly Master', 'Maintain a 30-day streak', '👑', 'general', 1000, '{"type": "streak", "value": 30}'),
  ('shape_perfect', 'Perfect Shape', 'Score 10/10 on Country Shape Quiz', '✨', 'country_shape', 150, '{"type": "perfect_score", "mode": "country_shape"}'),
  ('shape_50', 'Shape Shifter', 'Identify 50 different countries by shape', '🔍', 'country_shape', 200, '{"type": "unique_correct", "mode": "country_shape", "value": 50}'),
  ('shape_all', 'Cartographer', 'Identify all 197 countries by shape', '🗺️', 'country_shape', 1000, '{"type": "unique_correct", "mode": "country_shape", "value": 197}'),
  ('name_50', 'Half the World', 'Name 50 countries in Name All mode', '📝', 'name_all', 100, '{"type": "score_threshold", "mode": "name_all", "value": 50}'),
  ('name_100', 'Century Club', 'Name 100 countries in Name All mode', '💯', 'name_all', 250, '{"type": "score_threshold", "mode": "name_all", "value": 100}'),
  ('name_150', 'Geography Buff', 'Name 150 countries in Name All mode', '🎓', 'name_all', 500, '{"type": "score_threshold", "mode": "name_all", "value": 150}'),
  ('name_all', 'World Champion', 'Name all 197 countries', '🏆', 'name_all', 2000, '{"type": "score_threshold", "mode": "name_all", "value": 197}'),
  ('speed_demon', 'Speed Demon', 'Name 100 countries in under 5 minutes', '⏱️', 'name_all', 500, '{"type": "speed_threshold", "mode": "name_all", "countries": 100, "seconds": 300}'),
  ('worldle_1', 'Lucky Guess', 'Guess the Worldle on the first try', '🍀', 'worldle', 300, '{"type": "guess_count", "mode": "worldle", "value": 1}'),
  ('worldle_streak_5', 'Five Alive', 'Complete 5 Worldle dailies in a row', '📅', 'worldle', 200, '{"type": "daily_streak", "mode": "worldle", "value": 5}'),
  ('sv_bullseye', 'Bullseye', 'Guess within 50km in Street View', '🎯', 'street_view', 150, '{"type": "distance_threshold", "mode": "street_view", "km": 50}'),
  ('sv_perfect', 'Perfect Round', 'Score 25000 in a Street View game (5 rounds)', '🌟', 'street_view', 500, '{"type": "perfect_score", "mode": "street_view"}'),
  ('sv_continent', 'Continental', 'Correctly identify locations on all 6 continents', '✈️', 'street_view', 300, '{"type": "all_continents", "mode": "street_view"}'),
  ('level_5', 'Rising Star', 'Reach level 5', '⭐', 'general', 100, '{"type": "level", "value": 5}'),
  ('level_10', 'Seasoned Explorer', 'Reach level 10', '🌟', 'general', 250, '{"type": "level", "value": 10}'),
  ('level_25', 'Geography Expert', 'Reach level 25', '💫', 'general', 750, '{"type": "level", "value": 25}'),
  ('level_50', 'Grand Master', 'Reach level 50', '🏅', 'general', 2000, '{"type": "level", "value": 50}'),
  ('friend_first', 'Social Butterfly', 'Add your first friend', '🤝', 'general', 50, '{"type": "friends", "value": 1}'),
  ('daily_first', 'Daily Dose', 'Complete your first daily challenge', '📰', 'general', 50, '{"type": "daily_completed", "value": 1}')
ON CONFLICT (id) DO NOTHING;
