import type { Country } from "@/types/geo";

export const countries: Country[] = [
  // ============ AFRICA ============
  {
    code: "DZ",
    code3: "DZA",
    name: "Algeria",
    officialName: "People's Democratic Republic of Algeria",
    alternateNames: [],
    capital: "Algiers",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 28.0339,
    lng: 1.6596,
    population: 44700000,
    areaKm2: 2381741,
    flag: "🇩🇿",
  },
  {
    code: "AO",
    code3: "AGO",
    name: "Angola",
    officialName: "Republic of Angola",
    alternateNames: [],
    capital: "Luanda",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: -11.2027,
    lng: 17.8739,
    population: 33900000,
    areaKm2: 1246700,
    flag: "🇦🇴",
  },
  {
    code: "BJ",
    code3: "BEN",
    name: "Benin",
    officialName: "Republic of Benin",
    alternateNames: ["Dahomey"],
    capital: "Porto-Novo",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 9.3077,
    lng: 2.3158,
    population: 12500000,
    areaKm2: 112622,
    flag: "🇧🇯",
  },
  {
    code: "BW",
    code3: "BWA",
    name: "Botswana",
    officialName: "Republic of Botswana",
    alternateNames: [],
    capital: "Gaborone",
    continent: "Africa",
    subregion: "Southern Africa",
    lat: -22.3285,
    lng: 24.6849,
    population: 2400000,
    areaKm2: 581730,
    flag: "🇧🇼",
  },
  {
    code: "BF",
    code3: "BFA",
    name: "Burkina Faso",
    officialName: "Burkina Faso",
    alternateNames: ["Upper Volta"],
    capital: "Ouagadougou",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 12.2383,
    lng: -1.5616,
    population: 21500000,
    areaKm2: 274200,
    flag: "🇧🇫",
  },
  {
    code: "BI",
    code3: "BDI",
    name: "Burundi",
    officialName: "Republic of Burundi",
    alternateNames: [],
    capital: "Gitega",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -3.3731,
    lng: 29.9189,
    population: 12300000,
    areaKm2: 27834,
    flag: "🇧🇮",
  },
  {
    code: "CV",
    code3: "CPV",
    name: "Cape Verde",
    officialName: "Republic of Cabo Verde",
    alternateNames: ["Cabo Verde"],
    capital: "Praia",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 16.5388,
    lng: -23.0418,
    population: 568000,
    areaKm2: 4033,
    flag: "🇨🇻",
  },
  {
    code: "CM",
    code3: "CMR",
    name: "Cameroon",
    officialName: "Republic of Cameroon",
    alternateNames: [],
    capital: "Yaoundé",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: 7.3697,
    lng: 12.3547,
    population: 27200000,
    areaKm2: 475442,
    flag: "🇨🇲",
  },
  {
    code: "CF",
    code3: "CAF",
    name: "Central African Republic",
    officialName: "Central African Republic",
    alternateNames: ["CAR"],
    capital: "Bangui",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: 6.6111,
    lng: 20.9394,
    population: 4900000,
    areaKm2: 622984,
    flag: "🇨🇫",
  },
  {
    code: "TD",
    code3: "TCD",
    name: "Chad",
    officialName: "Republic of Chad",
    alternateNames: ["Tchad"],
    capital: "N'Djamena",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: 15.4542,
    lng: 18.7322,
    population: 16900000,
    areaKm2: 1284000,
    flag: "🇹🇩",
  },
  {
    code: "KM",
    code3: "COM",
    name: "Comoros",
    officialName: "Union of the Comoros",
    alternateNames: [],
    capital: "Moroni",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -11.6455,
    lng: 43.3333,
    population: 900000,
    areaKm2: 2235,
    flag: "🇰🇲",
  },
  {
    code: "CG",
    code3: "COG",
    name: "Republic of the Congo",
    officialName: "Republic of the Congo",
    alternateNames: ["Congo-Brazzaville", "Congo Republic"],
    capital: "Brazzaville",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: -0.228,
    lng: 15.8277,
    population: 5700000,
    areaKm2: 342000,
    flag: "🇨🇬",
  },
  {
    code: "CD",
    code3: "COD",
    name: "Democratic Republic of the Congo",
    officialName: "Democratic Republic of the Congo",
    alternateNames: ["DRC", "Congo-Kinshasa", "DR Congo", "Zaire"],
    capital: "Kinshasa",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: -4.0383,
    lng: 21.7587,
    population: 99000000,
    areaKm2: 2344858,
    flag: "🇨🇩",
  },
  {
    code: "CI",
    code3: "CIV",
    name: "Ivory Coast",
    officialName: "Republic of Côte d'Ivoire",
    alternateNames: ["Côte d'Ivoire", "Cote d'Ivoire"],
    capital: "Yamoussoukro",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 7.54,
    lng: -5.5471,
    population: 27700000,
    areaKm2: 322463,
    flag: "🇨🇮",
  },
  {
    code: "DJ",
    code3: "DJI",
    name: "Djibouti",
    officialName: "Republic of Djibouti",
    alternateNames: [],
    capital: "Djibouti",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 11.8251,
    lng: 42.5903,
    population: 1000000,
    areaKm2: 23200,
    flag: "🇩🇯",
  },
  {
    code: "EG",
    code3: "EGY",
    name: "Egypt",
    officialName: "Arab Republic of Egypt",
    alternateNames: ["Misr"],
    capital: "Cairo",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 26.8206,
    lng: 30.8025,
    population: 104300000,
    areaKm2: 1002450,
    flag: "🇪🇬",
  },
  {
    code: "GQ",
    code3: "GNQ",
    name: "Equatorial Guinea",
    officialName: "Republic of Equatorial Guinea",
    alternateNames: [],
    capital: "Malabo",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: 1.6508,
    lng: 10.2679,
    population: 1500000,
    areaKm2: 28051,
    flag: "🇬🇶",
  },
  {
    code: "ER",
    code3: "ERI",
    name: "Eritrea",
    officialName: "State of Eritrea",
    alternateNames: [],
    capital: "Asmara",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 15.1794,
    lng: 39.7823,
    population: 3600000,
    areaKm2: 117600,
    flag: "🇪🇷",
  },
  {
    code: "SZ",
    code3: "SWZ",
    name: "Eswatini",
    officialName: "Kingdom of Eswatini",
    alternateNames: ["Swaziland"],
    capital: "Mbabane",
    continent: "Africa",
    subregion: "Southern Africa",
    lat: -26.5225,
    lng: 31.4659,
    population: 1200000,
    areaKm2: 17364,
    flag: "🇸🇿",
  },
  {
    code: "ET",
    code3: "ETH",
    name: "Ethiopia",
    officialName: "Federal Democratic Republic of Ethiopia",
    alternateNames: ["Abyssinia"],
    capital: "Addis Ababa",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 9.145,
    lng: 40.4897,
    population: 120300000,
    areaKm2: 1104300,
    flag: "🇪🇹",
  },
  {
    code: "GA",
    code3: "GAB",
    name: "Gabon",
    officialName: "Gabonese Republic",
    alternateNames: [],
    capital: "Libreville",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: -0.8037,
    lng: 11.6094,
    population: 2300000,
    areaKm2: 267668,
    flag: "🇬🇦",
  },
  {
    code: "GM",
    code3: "GMB",
    name: "Gambia",
    officialName: "Republic of The Gambia",
    alternateNames: ["The Gambia"],
    capital: "Banjul",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 13.4432,
    lng: -15.3101,
    population: 2500000,
    areaKm2: 11295,
    flag: "🇬🇲",
  },
  {
    code: "GH",
    code3: "GHA",
    name: "Ghana",
    officialName: "Republic of Ghana",
    alternateNames: [],
    capital: "Accra",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 7.9465,
    lng: -1.0232,
    population: 32800000,
    areaKm2: 238533,
    flag: "🇬🇭",
  },
  {
    code: "GN",
    code3: "GIN",
    name: "Guinea",
    officialName: "Republic of Guinea",
    alternateNames: ["Guinea-Conakry"],
    capital: "Conakry",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 9.9456,
    lng: -9.6966,
    population: 13500000,
    areaKm2: 245857,
    flag: "🇬🇳",
  },
  {
    code: "GW",
    code3: "GNB",
    name: "Guinea-Bissau",
    officialName: "Republic of Guinea-Bissau",
    alternateNames: [],
    capital: "Bissau",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 11.8037,
    lng: -15.1804,
    population: 2100000,
    areaKm2: 36125,
    flag: "🇬🇼",
  },
  {
    code: "KE",
    code3: "KEN",
    name: "Kenya",
    officialName: "Republic of Kenya",
    alternateNames: [],
    capital: "Nairobi",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -0.0236,
    lng: 37.9062,
    population: 54700000,
    areaKm2: 580367,
    flag: "🇰🇪",
  },
  {
    code: "LS",
    code3: "LSO",
    name: "Lesotho",
    officialName: "Kingdom of Lesotho",
    alternateNames: [],
    capital: "Maseru",
    continent: "Africa",
    subregion: "Southern Africa",
    lat: -29.61,
    lng: 28.2336,
    population: 2200000,
    areaKm2: 30355,
    flag: "🇱🇸",
  },
  {
    code: "LR",
    code3: "LBR",
    name: "Liberia",
    officialName: "Republic of Liberia",
    alternateNames: [],
    capital: "Monrovia",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 6.4281,
    lng: -9.4295,
    population: 5200000,
    areaKm2: 111369,
    flag: "🇱🇷",
  },
  {
    code: "LY",
    code3: "LBY",
    name: "Libya",
    officialName: "State of Libya",
    alternateNames: [],
    capital: "Tripoli",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 26.3351,
    lng: 17.2283,
    population: 7000000,
    areaKm2: 1759540,
    flag: "🇱🇾",
  },
  {
    code: "MG",
    code3: "MDG",
    name: "Madagascar",
    officialName: "Republic of Madagascar",
    alternateNames: [],
    capital: "Antananarivo",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -18.7669,
    lng: 46.8691,
    population: 28400000,
    areaKm2: 587041,
    flag: "🇲🇬",
  },
  {
    code: "MW",
    code3: "MWI",
    name: "Malawi",
    officialName: "Republic of Malawi",
    alternateNames: ["Nyasaland"],
    capital: "Lilongwe",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -13.2543,
    lng: 34.3015,
    population: 19600000,
    areaKm2: 118484,
    flag: "🇲🇼",
  },
  {
    code: "ML",
    code3: "MLI",
    name: "Mali",
    officialName: "Republic of Mali",
    alternateNames: [],
    capital: "Bamako",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 17.5707,
    lng: -3.9962,
    population: 21400000,
    areaKm2: 1240192,
    flag: "🇲🇱",
  },
  {
    code: "MR",
    code3: "MRT",
    name: "Mauritania",
    officialName: "Islamic Republic of Mauritania",
    alternateNames: [],
    capital: "Nouakchott",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 21.0079,
    lng: -10.9408,
    population: 4700000,
    areaKm2: 1030700,
    flag: "🇲🇷",
  },
  {
    code: "MU",
    code3: "MUS",
    name: "Mauritius",
    officialName: "Republic of Mauritius",
    alternateNames: [],
    capital: "Port Louis",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -20.3484,
    lng: 57.5522,
    population: 1300000,
    areaKm2: 2040,
    flag: "🇲🇺",
  },
  {
    code: "MA",
    code3: "MAR",
    name: "Morocco",
    officialName: "Kingdom of Morocco",
    alternateNames: ["Al-Maghrib"],
    capital: "Rabat",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 31.7917,
    lng: -7.0926,
    population: 37300000,
    areaKm2: 446550,
    flag: "🇲🇦",
  },
  {
    code: "MZ",
    code3: "MOZ",
    name: "Mozambique",
    officialName: "Republic of Mozambique",
    alternateNames: [],
    capital: "Maputo",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -18.6657,
    lng: 35.5296,
    population: 32200000,
    areaKm2: 801590,
    flag: "🇲🇿",
  },
  {
    code: "NA",
    code3: "NAM",
    name: "Namibia",
    officialName: "Republic of Namibia",
    alternateNames: [],
    capital: "Windhoek",
    continent: "Africa",
    subregion: "Southern Africa",
    lat: -22.9576,
    lng: 18.4904,
    population: 2600000,
    areaKm2: 825615,
    flag: "🇳🇦",
  },
  {
    code: "NE",
    code3: "NER",
    name: "Niger",
    officialName: "Republic of the Niger",
    alternateNames: [],
    capital: "Niamey",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 17.6078,
    lng: 8.0817,
    population: 25100000,
    areaKm2: 1267000,
    flag: "🇳🇪",
  },
  {
    code: "NG",
    code3: "NGA",
    name: "Nigeria",
    officialName: "Federal Republic of Nigeria",
    alternateNames: [],
    capital: "Abuja",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 9.082,
    lng: 8.6753,
    population: 218500000,
    areaKm2: 923768,
    flag: "🇳🇬",
  },
  {
    code: "RW",
    code3: "RWA",
    name: "Rwanda",
    officialName: "Republic of Rwanda",
    alternateNames: [],
    capital: "Kigali",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -1.9403,
    lng: 29.8739,
    population: 13500000,
    areaKm2: 26338,
    flag: "🇷🇼",
  },
  {
    code: "ST",
    code3: "STP",
    name: "São Tomé and Príncipe",
    officialName: "Democratic Republic of São Tomé and Príncipe",
    alternateNames: ["Sao Tome and Principe", "Sao Tome"],
    capital: "São Tomé",
    continent: "Africa",
    subregion: "Middle Africa",
    lat: 0.1864,
    lng: 6.6131,
    population: 220000,
    areaKm2: 964,
    flag: "🇸🇹",
  },
  {
    code: "SN",
    code3: "SEN",
    name: "Senegal",
    officialName: "Republic of Senegal",
    alternateNames: [],
    capital: "Dakar",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 14.4974,
    lng: -14.4524,
    population: 17200000,
    areaKm2: 196722,
    flag: "🇸🇳",
  },
  {
    code: "SC",
    code3: "SYC",
    name: "Seychelles",
    officialName: "Republic of Seychelles",
    alternateNames: [],
    capital: "Victoria",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -4.6796,
    lng: 55.492,
    population: 99000,
    areaKm2: 459,
    flag: "🇸🇨",
  },
  {
    code: "SL",
    code3: "SLE",
    name: "Sierra Leone",
    officialName: "Republic of Sierra Leone",
    alternateNames: [],
    capital: "Freetown",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 8.4606,
    lng: -11.7799,
    population: 8200000,
    areaKm2: 71740,
    flag: "🇸🇱",
  },
  {
    code: "SO",
    code3: "SOM",
    name: "Somalia",
    officialName: "Federal Republic of Somalia",
    alternateNames: [],
    capital: "Mogadishu",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 5.1521,
    lng: 46.1996,
    population: 17100000,
    areaKm2: 637657,
    flag: "🇸🇴",
  },
  {
    code: "ZA",
    code3: "ZAF",
    name: "South Africa",
    officialName: "Republic of South Africa",
    alternateNames: ["RSA"],
    capital: "Pretoria",
    continent: "Africa",
    subregion: "Southern Africa",
    lat: -30.5595,
    lng: 22.9375,
    population: 60400000,
    areaKm2: 1221037,
    flag: "🇿🇦",
  },
  {
    code: "SS",
    code3: "SSD",
    name: "South Sudan",
    officialName: "Republic of South Sudan",
    alternateNames: [],
    capital: "Juba",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 6.877,
    lng: 31.307,
    population: 11400000,
    areaKm2: 619745,
    flag: "🇸🇸",
  },
  {
    code: "SD",
    code3: "SDN",
    name: "Sudan",
    officialName: "Republic of the Sudan",
    alternateNames: [],
    capital: "Khartoum",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 12.8628,
    lng: 30.2176,
    population: 44900000,
    areaKm2: 1861484,
    flag: "🇸🇩",
  },
  {
    code: "TZ",
    code3: "TZA",
    name: "Tanzania",
    officialName: "United Republic of Tanzania",
    alternateNames: [],
    capital: "Dodoma",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -6.369,
    lng: 34.8888,
    population: 63600000,
    areaKm2: 945087,
    flag: "🇹🇿",
  },
  {
    code: "TG",
    code3: "TGO",
    name: "Togo",
    officialName: "Togolese Republic",
    alternateNames: [],
    capital: "Lomé",
    continent: "Africa",
    subregion: "Western Africa",
    lat: 8.6195,
    lng: 0.8248,
    population: 8600000,
    areaKm2: 56785,
    flag: "🇹🇬",
  },
  {
    code: "TN",
    code3: "TUN",
    name: "Tunisia",
    officialName: "Republic of Tunisia",
    alternateNames: [],
    capital: "Tunis",
    continent: "Africa",
    subregion: "Northern Africa",
    lat: 33.8869,
    lng: 9.5375,
    population: 12000000,
    areaKm2: 163610,
    flag: "🇹🇳",
  },
  {
    code: "UG",
    code3: "UGA",
    name: "Uganda",
    officialName: "Republic of Uganda",
    alternateNames: [],
    capital: "Kampala",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: 1.3733,
    lng: 32.2903,
    population: 47200000,
    areaKm2: 241038,
    flag: "🇺🇬",
  },
  {
    code: "ZM",
    code3: "ZMB",
    name: "Zambia",
    officialName: "Republic of Zambia",
    alternateNames: [],
    capital: "Lusaka",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -13.1339,
    lng: 27.8493,
    population: 19500000,
    areaKm2: 752612,
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    code3: "ZWE",
    name: "Zimbabwe",
    officialName: "Republic of Zimbabwe",
    alternateNames: ["Rhodesia"],
    capital: "Harare",
    continent: "Africa",
    subregion: "Eastern Africa",
    lat: -19.0154,
    lng: 29.1549,
    population: 15900000,
    areaKm2: 390757,
    flag: "🇿🇼",
  },

  // ============ ASIA ============
  {
    code: "AF",
    code3: "AFG",
    name: "Afghanistan",
    officialName: "Islamic Emirate of Afghanistan",
    alternateNames: [],
    capital: "Kabul",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 33.9391,
    lng: 67.71,
    population: 40100000,
    areaKm2: 652230,
    flag: "🇦🇫",
  },
  {
    code: "AM",
    code3: "ARM",
    name: "Armenia",
    officialName: "Republic of Armenia",
    alternateNames: ["Hayastan"],
    capital: "Yerevan",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 40.0691,
    lng: 45.0382,
    population: 3000000,
    areaKm2: 29743,
    flag: "🇦🇲",
  },
  {
    code: "AZ",
    code3: "AZE",
    name: "Azerbaijan",
    officialName: "Republic of Azerbaijan",
    alternateNames: [],
    capital: "Baku",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 40.1431,
    lng: 47.5769,
    population: 10200000,
    areaKm2: 86600,
    flag: "🇦🇿",
  },
  {
    code: "BH",
    code3: "BHR",
    name: "Bahrain",
    officialName: "Kingdom of Bahrain",
    alternateNames: [],
    capital: "Manama",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 26.0667,
    lng: 50.5577,
    population: 1500000,
    areaKm2: 765,
    flag: "🇧🇭",
  },
  {
    code: "BD",
    code3: "BGD",
    name: "Bangladesh",
    officialName: "People's Republic of Bangladesh",
    alternateNames: [],
    capital: "Dhaka",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 23.685,
    lng: 90.3563,
    population: 169400000,
    areaKm2: 147570,
    flag: "🇧🇩",
  },
  {
    code: "BT",
    code3: "BTN",
    name: "Bhutan",
    officialName: "Kingdom of Bhutan",
    alternateNames: ["Druk Yul"],
    capital: "Thimphu",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 27.5142,
    lng: 90.4336,
    population: 780000,
    areaKm2: 38394,
    flag: "🇧🇹",
  },
  {
    code: "BN",
    code3: "BRN",
    name: "Brunei",
    officialName: "Nation of Brunei, the Abode of Peace",
    alternateNames: ["Brunei Darussalam"],
    capital: "Bandar Seri Begawan",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 4.5353,
    lng: 114.7277,
    population: 440000,
    areaKm2: 5765,
    flag: "🇧🇳",
  },
  {
    code: "KH",
    code3: "KHM",
    name: "Cambodia",
    officialName: "Kingdom of Cambodia",
    alternateNames: ["Kampuchea"],
    capital: "Phnom Penh",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 12.5657,
    lng: 104.991,
    population: 16900000,
    areaKm2: 181035,
    flag: "🇰🇭",
  },
  {
    code: "CN",
    code3: "CHN",
    name: "China",
    officialName: "People's Republic of China",
    alternateNames: ["PRC", "Zhongguo"],
    capital: "Beijing",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 35.8617,
    lng: 104.1954,
    population: 1412000000,
    areaKm2: 9596961,
    flag: "🇨🇳",
  },
  {
    code: "CY",
    code3: "CYP",
    name: "Cyprus",
    officialName: "Republic of Cyprus",
    alternateNames: [],
    capital: "Nicosia",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 35.1264,
    lng: 33.4299,
    population: 1200000,
    areaKm2: 9251,
    flag: "🇨🇾",
  },
  {
    code: "GE",
    code3: "GEO",
    name: "Georgia",
    officialName: "Georgia",
    alternateNames: ["Sakartvelo"],
    capital: "Tbilisi",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 42.3154,
    lng: 43.3569,
    population: 3700000,
    areaKm2: 69700,
    flag: "🇬🇪",
  },
  {
    code: "IN",
    code3: "IND",
    name: "India",
    officialName: "Republic of India",
    alternateNames: ["Bharat", "Hindustan"],
    capital: "New Delhi",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 20.5937,
    lng: 78.9629,
    population: 1428000000,
    areaKm2: 3287263,
    flag: "🇮🇳",
  },
  {
    code: "ID",
    code3: "IDN",
    name: "Indonesia",
    officialName: "Republic of Indonesia",
    alternateNames: [],
    capital: "Jakarta",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: -0.7893,
    lng: 113.9213,
    population: 277500000,
    areaKm2: 1904569,
    flag: "🇮🇩",
  },
  {
    code: "IR",
    code3: "IRN",
    name: "Iran",
    officialName: "Islamic Republic of Iran",
    alternateNames: ["Persia"],
    capital: "Tehran",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 32.4279,
    lng: 53.688,
    population: 87900000,
    areaKm2: 1648195,
    flag: "🇮🇷",
  },
  {
    code: "IQ",
    code3: "IRQ",
    name: "Iraq",
    officialName: "Republic of Iraq",
    alternateNames: [],
    capital: "Baghdad",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 33.2232,
    lng: 43.6793,
    population: 42200000,
    areaKm2: 438317,
    flag: "🇮🇶",
  },
  {
    code: "IL",
    code3: "ISR",
    name: "Israel",
    officialName: "State of Israel",
    alternateNames: [],
    capital: "Jerusalem",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 31.0461,
    lng: 34.8516,
    population: 9400000,
    areaKm2: 20770,
    flag: "🇮🇱",
  },
  {
    code: "JP",
    code3: "JPN",
    name: "Japan",
    officialName: "Japan",
    alternateNames: ["Nippon", "Nihon"],
    capital: "Tokyo",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 36.2048,
    lng: 138.2529,
    population: 125700000,
    areaKm2: 377975,
    flag: "🇯🇵",
  },
  {
    code: "JO",
    code3: "JOR",
    name: "Jordan",
    officialName: "Hashemite Kingdom of Jordan",
    alternateNames: [],
    capital: "Amman",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 30.5852,
    lng: 36.2384,
    population: 11100000,
    areaKm2: 89342,
    flag: "🇯🇴",
  },
  {
    code: "KZ",
    code3: "KAZ",
    name: "Kazakhstan",
    officialName: "Republic of Kazakhstan",
    alternateNames: [],
    capital: "Astana",
    continent: "Asia",
    subregion: "Central Asia",
    lat: 48.0196,
    lng: 66.9237,
    population: 19400000,
    areaKm2: 2724900,
    flag: "🇰🇿",
  },
  {
    code: "KW",
    code3: "KWT",
    name: "Kuwait",
    officialName: "State of Kuwait",
    alternateNames: [],
    capital: "Kuwait City",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 29.3117,
    lng: 47.4818,
    population: 4300000,
    areaKm2: 17818,
    flag: "🇰🇼",
  },
  {
    code: "KG",
    code3: "KGZ",
    name: "Kyrgyzstan",
    officialName: "Kyrgyz Republic",
    alternateNames: ["Kirghizia"],
    capital: "Bishkek",
    continent: "Asia",
    subregion: "Central Asia",
    lat: 41.2044,
    lng: 74.7661,
    population: 6700000,
    areaKm2: 199951,
    flag: "🇰🇬",
  },
  {
    code: "LA",
    code3: "LAO",
    name: "Laos",
    officialName: "Lao People's Democratic Republic",
    alternateNames: ["Lao"],
    capital: "Vientiane",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 19.8563,
    lng: 102.4955,
    population: 7400000,
    areaKm2: 236800,
    flag: "🇱🇦",
  },
  {
    code: "LB",
    code3: "LBN",
    name: "Lebanon",
    officialName: "Lebanese Republic",
    alternateNames: [],
    capital: "Beirut",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 33.8547,
    lng: 35.8623,
    population: 5500000,
    areaKm2: 10452,
    flag: "🇱🇧",
  },
  {
    code: "MY",
    code3: "MYS",
    name: "Malaysia",
    officialName: "Malaysia",
    alternateNames: [],
    capital: "Kuala Lumpur",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 4.2105,
    lng: 101.9758,
    population: 33200000,
    areaKm2: 330803,
    flag: "🇲🇾",
  },
  {
    code: "MV",
    code3: "MDV",
    name: "Maldives",
    officialName: "Republic of Maldives",
    alternateNames: [],
    capital: "Malé",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 3.2028,
    lng: 73.2207,
    population: 540000,
    areaKm2: 300,
    flag: "🇲🇻",
  },
  {
    code: "MN",
    code3: "MNG",
    name: "Mongolia",
    officialName: "Mongolia",
    alternateNames: [],
    capital: "Ulaanbaatar",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 46.8625,
    lng: 103.8467,
    population: 3400000,
    areaKm2: 1564116,
    flag: "🇲🇳",
  },
  {
    code: "MM",
    code3: "MMR",
    name: "Myanmar",
    officialName: "Republic of the Union of Myanmar",
    alternateNames: ["Burma"],
    capital: "Naypyidaw",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 21.9162,
    lng: 95.956,
    population: 54400000,
    areaKm2: 676578,
    flag: "🇲🇲",
  },
  {
    code: "NP",
    code3: "NPL",
    name: "Nepal",
    officialName: "Federal Democratic Republic of Nepal",
    alternateNames: [],
    capital: "Kathmandu",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 28.3949,
    lng: 84.124,
    population: 30000000,
    areaKm2: 147516,
    flag: "🇳🇵",
  },
  {
    code: "KP",
    code3: "PRK",
    name: "North Korea",
    officialName: "Democratic People's Republic of Korea",
    alternateNames: ["DPRK"],
    capital: "Pyongyang",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 40.3399,
    lng: 127.5101,
    population: 26000000,
    areaKm2: 120538,
    flag: "🇰🇵",
  },
  {
    code: "OM",
    code3: "OMN",
    name: "Oman",
    officialName: "Sultanate of Oman",
    alternateNames: [],
    capital: "Muscat",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 21.4735,
    lng: 55.9754,
    population: 5200000,
    areaKm2: 309500,
    flag: "🇴🇲",
  },
  {
    code: "PK",
    code3: "PAK",
    name: "Pakistan",
    officialName: "Islamic Republic of Pakistan",
    alternateNames: [],
    capital: "Islamabad",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 30.3753,
    lng: 69.3451,
    population: 231400000,
    areaKm2: 881913,
    flag: "🇵🇰",
  },
  {
    code: "PS",
    code3: "PSE",
    name: "Palestine",
    officialName: "State of Palestine",
    alternateNames: ["Palestinian Territories", "West Bank and Gaza"],
    capital: "Ramallah",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 31.9522,
    lng: 35.2332,
    population: 5300000,
    areaKm2: 6020,
    flag: "🇵🇸",
  },
  {
    code: "PH",
    code3: "PHL",
    name: "Philippines",
    officialName: "Republic of the Philippines",
    alternateNames: ["The Philippines"],
    capital: "Manila",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 12.8797,
    lng: 121.774,
    population: 113900000,
    areaKm2: 300000,
    flag: "🇵🇭",
  },
  {
    code: "QA",
    code3: "QAT",
    name: "Qatar",
    officialName: "State of Qatar",
    alternateNames: [],
    capital: "Doha",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 25.3548,
    lng: 51.1839,
    population: 2900000,
    areaKm2: 11586,
    flag: "🇶🇦",
  },
  {
    code: "SA",
    code3: "SAU",
    name: "Saudi Arabia",
    officialName: "Kingdom of Saudi Arabia",
    alternateNames: ["KSA"],
    capital: "Riyadh",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 23.8859,
    lng: 45.0792,
    population: 36000000,
    areaKm2: 2149690,
    flag: "🇸🇦",
  },
  {
    code: "SG",
    code3: "SGP",
    name: "Singapore",
    officialName: "Republic of Singapore",
    alternateNames: [],
    capital: "Singapore",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 1.3521,
    lng: 103.8198,
    population: 5700000,
    areaKm2: 728,
    flag: "🇸🇬",
  },
  {
    code: "KR",
    code3: "KOR",
    name: "South Korea",
    officialName: "Republic of Korea",
    alternateNames: ["Korea", "Republic of Korea", "ROK"],
    capital: "Seoul",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 35.9078,
    lng: 127.7669,
    population: 51700000,
    areaKm2: 100210,
    flag: "🇰🇷",
  },
  {
    code: "LK",
    code3: "LKA",
    name: "Sri Lanka",
    officialName: "Democratic Socialist Republic of Sri Lanka",
    alternateNames: ["Ceylon"],
    capital: "Sri Jayawardenepura Kotte",
    continent: "Asia",
    subregion: "Southern Asia",
    lat: 7.8731,
    lng: 80.7718,
    population: 22200000,
    areaKm2: 65610,
    flag: "🇱🇰",
  },
  {
    code: "SY",
    code3: "SYR",
    name: "Syria",
    officialName: "Syrian Arab Republic",
    alternateNames: [],
    capital: "Damascus",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 34.8021,
    lng: 38.9968,
    population: 21300000,
    areaKm2: 185180,
    flag: "🇸🇾",
  },
  {
    code: "TW",
    code3: "TWN",
    name: "Taiwan",
    officialName: "Republic of China",
    alternateNames: ["Chinese Taipei", "Formosa", "ROC"],
    capital: "Taipei",
    continent: "Asia",
    subregion: "Eastern Asia",
    lat: 23.6978,
    lng: 120.9605,
    population: 23600000,
    areaKm2: 36193,
    flag: "🇹🇼",
  },
  {
    code: "TJ",
    code3: "TJK",
    name: "Tajikistan",
    officialName: "Republic of Tajikistan",
    alternateNames: [],
    capital: "Dushanbe",
    continent: "Asia",
    subregion: "Central Asia",
    lat: 38.861,
    lng: 71.2761,
    population: 9900000,
    areaKm2: 143100,
    flag: "🇹🇯",
  },
  {
    code: "TH",
    code3: "THA",
    name: "Thailand",
    officialName: "Kingdom of Thailand",
    alternateNames: ["Siam"],
    capital: "Bangkok",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 15.87,
    lng: 100.9925,
    population: 71800000,
    areaKm2: 513120,
    flag: "🇹🇭",
  },
  {
    code: "TL",
    code3: "TLS",
    name: "Timor-Leste",
    officialName: "Democratic Republic of Timor-Leste",
    alternateNames: ["East Timor"],
    capital: "Dili",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: -8.8742,
    lng: 125.7275,
    population: 1300000,
    areaKm2: 14874,
    flag: "🇹🇱",
  },
  {
    code: "TR",
    code3: "TUR",
    name: "Turkey",
    officialName: "Republic of Türkiye",
    alternateNames: ["Türkiye", "Turkiye"],
    capital: "Ankara",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 38.9637,
    lng: 35.2433,
    population: 85300000,
    areaKm2: 783562,
    flag: "🇹🇷",
  },
  {
    code: "TM",
    code3: "TKM",
    name: "Turkmenistan",
    officialName: "Turkmenistan",
    alternateNames: [],
    capital: "Ashgabat",
    continent: "Asia",
    subregion: "Central Asia",
    lat: 38.9697,
    lng: 59.5563,
    population: 6300000,
    areaKm2: 488100,
    flag: "🇹🇲",
  },
  {
    code: "AE",
    code3: "ARE",
    name: "United Arab Emirates",
    officialName: "United Arab Emirates",
    alternateNames: ["UAE", "Emirates"],
    capital: "Abu Dhabi",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 23.4241,
    lng: 53.8478,
    population: 10000000,
    areaKm2: 83600,
    flag: "🇦🇪",
  },
  {
    code: "UZ",
    code3: "UZB",
    name: "Uzbekistan",
    officialName: "Republic of Uzbekistan",
    alternateNames: [],
    capital: "Tashkent",
    continent: "Asia",
    subregion: "Central Asia",
    lat: 41.3775,
    lng: 64.5853,
    population: 35300000,
    areaKm2: 447400,
    flag: "🇺🇿",
  },
  {
    code: "VN",
    code3: "VNM",
    name: "Vietnam",
    officialName: "Socialist Republic of Vietnam",
    alternateNames: ["Viet Nam"],
    capital: "Hanoi",
    continent: "Asia",
    subregion: "South-Eastern Asia",
    lat: 14.0583,
    lng: 108.2772,
    population: 99500000,
    areaKm2: 331212,
    flag: "🇻🇳",
  },
  {
    code: "YE",
    code3: "YEM",
    name: "Yemen",
    officialName: "Republic of Yemen",
    alternateNames: [],
    capital: "Sana'a",
    continent: "Asia",
    subregion: "Western Asia",
    lat: 15.5527,
    lng: 48.5164,
    population: 33700000,
    areaKm2: 527968,
    flag: "🇾🇪",
  },

  // ============ EUROPE ============
  {
    code: "AL",
    code3: "ALB",
    name: "Albania",
    officialName: "Republic of Albania",
    alternateNames: ["Shqipëri"],
    capital: "Tirana",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 41.1533,
    lng: 20.1683,
    population: 2800000,
    areaKm2: 28748,
    flag: "🇦🇱",
  },
  {
    code: "AD",
    code3: "AND",
    name: "Andorra",
    officialName: "Principality of Andorra",
    alternateNames: [],
    capital: "Andorra la Vella",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 42.5063,
    lng: 1.5218,
    population: 80000,
    areaKm2: 468,
    flag: "🇦🇩",
  },
  {
    code: "AT",
    code3: "AUT",
    name: "Austria",
    officialName: "Republic of Austria",
    alternateNames: ["Österreich"],
    capital: "Vienna",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 47.5162,
    lng: 14.5501,
    population: 9100000,
    areaKm2: 83871,
    flag: "🇦🇹",
  },
  {
    code: "BY",
    code3: "BLR",
    name: "Belarus",
    officialName: "Republic of Belarus",
    alternateNames: ["Byelorussia"],
    capital: "Minsk",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 53.7098,
    lng: 27.9534,
    population: 9400000,
    areaKm2: 207600,
    flag: "🇧🇾",
  },
  {
    code: "BE",
    code3: "BEL",
    name: "Belgium",
    officialName: "Kingdom of Belgium",
    alternateNames: ["België", "Belgique"],
    capital: "Brussels",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 50.5039,
    lng: 4.4699,
    population: 11600000,
    areaKm2: 30528,
    flag: "🇧🇪",
  },
  {
    code: "BA",
    code3: "BIH",
    name: "Bosnia and Herzegovina",
    officialName: "Bosnia and Herzegovina",
    alternateNames: ["Bosnia", "BiH"],
    capital: "Sarajevo",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 43.9159,
    lng: 17.6791,
    population: 3300000,
    areaKm2: 51197,
    flag: "🇧🇦",
  },
  {
    code: "BG",
    code3: "BGR",
    name: "Bulgaria",
    officialName: "Republic of Bulgaria",
    alternateNames: [],
    capital: "Sofia",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 42.7339,
    lng: 25.4858,
    population: 6900000,
    areaKm2: 110879,
    flag: "🇧🇬",
  },
  {
    code: "HR",
    code3: "HRV",
    name: "Croatia",
    officialName: "Republic of Croatia",
    alternateNames: ["Hrvatska"],
    capital: "Zagreb",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 45.1,
    lng: 15.2,
    population: 3900000,
    areaKm2: 56594,
    flag: "🇭🇷",
  },
  {
    code: "CZ",
    code3: "CZE",
    name: "Czech Republic",
    officialName: "Czech Republic",
    alternateNames: ["Czechia", "Česko"],
    capital: "Prague",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 49.8175,
    lng: 15.473,
    population: 10700000,
    areaKm2: 78867,
    flag: "🇨🇿",
  },
  {
    code: "DK",
    code3: "DNK",
    name: "Denmark",
    officialName: "Kingdom of Denmark",
    alternateNames: ["Danmark"],
    capital: "Copenhagen",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 56.2639,
    lng: 9.5018,
    population: 5900000,
    areaKm2: 43094,
    flag: "🇩🇰",
  },
  {
    code: "EE",
    code3: "EST",
    name: "Estonia",
    officialName: "Republic of Estonia",
    alternateNames: ["Eesti"],
    capital: "Tallinn",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 58.5953,
    lng: 25.0136,
    population: 1300000,
    areaKm2: 45228,
    flag: "🇪🇪",
  },
  {
    code: "FI",
    code3: "FIN",
    name: "Finland",
    officialName: "Republic of Finland",
    alternateNames: ["Suomi"],
    capital: "Helsinki",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 61.9241,
    lng: 25.7482,
    population: 5500000,
    areaKm2: 338424,
    flag: "🇫🇮",
  },
  {
    code: "FR",
    code3: "FRA",
    name: "France",
    officialName: "French Republic",
    alternateNames: [],
    capital: "Paris",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 46.2276,
    lng: 2.2137,
    population: 67800000,
    areaKm2: 643801,
    flag: "🇫🇷",
  },
  {
    code: "DE",
    code3: "DEU",
    name: "Germany",
    officialName: "Federal Republic of Germany",
    alternateNames: ["Deutschland"],
    capital: "Berlin",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 51.1657,
    lng: 10.4515,
    population: 83200000,
    areaKm2: 357114,
    flag: "🇩🇪",
  },
  {
    code: "GR",
    code3: "GRC",
    name: "Greece",
    officialName: "Hellenic Republic",
    alternateNames: ["Hellas", "Ellada"],
    capital: "Athens",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 39.0742,
    lng: 21.8243,
    population: 10700000,
    areaKm2: 131957,
    flag: "🇬🇷",
  },
  {
    code: "HU",
    code3: "HUN",
    name: "Hungary",
    officialName: "Hungary",
    alternateNames: ["Magyarország"],
    capital: "Budapest",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 47.1625,
    lng: 19.5033,
    population: 9700000,
    areaKm2: 93028,
    flag: "🇭🇺",
  },
  {
    code: "IS",
    code3: "ISL",
    name: "Iceland",
    officialName: "Iceland",
    alternateNames: ["Ísland"],
    capital: "Reykjavik",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 64.9631,
    lng: -19.0208,
    population: 370000,
    areaKm2: 103000,
    flag: "🇮🇸",
  },
  {
    code: "IE",
    code3: "IRL",
    name: "Ireland",
    officialName: "Republic of Ireland",
    alternateNames: ["Éire", "Eire"],
    capital: "Dublin",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 53.1424,
    lng: -7.6921,
    population: 5100000,
    areaKm2: 70273,
    flag: "🇮🇪",
  },
  {
    code: "IT",
    code3: "ITA",
    name: "Italy",
    officialName: "Italian Republic",
    alternateNames: ["Italia"],
    capital: "Rome",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 41.8719,
    lng: 12.5674,
    population: 59100000,
    areaKm2: 301340,
    flag: "🇮🇹",
  },
  {
    code: "XK",
    code3: "XKX",
    name: "Kosovo",
    officialName: "Republic of Kosovo",
    alternateNames: ["Kosova"],
    capital: "Pristina",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 42.6026,
    lng: 20.903,
    population: 1800000,
    areaKm2: 10887,
    flag: "🇽🇰",
  },
  {
    code: "LV",
    code3: "LVA",
    name: "Latvia",
    officialName: "Republic of Latvia",
    alternateNames: ["Latvija"],
    capital: "Riga",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 56.8796,
    lng: 24.6032,
    population: 1900000,
    areaKm2: 64559,
    flag: "🇱🇻",
  },
  {
    code: "LI",
    code3: "LIE",
    name: "Liechtenstein",
    officialName: "Principality of Liechtenstein",
    alternateNames: [],
    capital: "Vaduz",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 47.166,
    lng: 9.5554,
    population: 39000,
    areaKm2: 160,
    flag: "🇱🇮",
  },
  {
    code: "LT",
    code3: "LTU",
    name: "Lithuania",
    officialName: "Republic of Lithuania",
    alternateNames: ["Lietuva"],
    capital: "Vilnius",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 55.1694,
    lng: 23.8813,
    population: 2800000,
    areaKm2: 65300,
    flag: "🇱🇹",
  },
  {
    code: "LU",
    code3: "LUX",
    name: "Luxembourg",
    officialName: "Grand Duchy of Luxembourg",
    alternateNames: ["Luxemburg"],
    capital: "Luxembourg",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 49.8153,
    lng: 6.1296,
    population: 640000,
    areaKm2: 2586,
    flag: "🇱🇺",
  },
  {
    code: "MT",
    code3: "MLT",
    name: "Malta",
    officialName: "Republic of Malta",
    alternateNames: [],
    capital: "Valletta",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 35.9375,
    lng: 14.3754,
    population: 520000,
    areaKm2: 316,
    flag: "🇲🇹",
  },
  {
    code: "MD",
    code3: "MDA",
    name: "Moldova",
    officialName: "Republic of Moldova",
    alternateNames: [],
    capital: "Chișinău",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 47.4116,
    lng: 28.3699,
    population: 2600000,
    areaKm2: 33851,
    flag: "🇲🇩",
  },
  {
    code: "MC",
    code3: "MCO",
    name: "Monaco",
    officialName: "Principality of Monaco",
    alternateNames: [],
    capital: "Monaco",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 43.7384,
    lng: 7.4246,
    population: 39000,
    areaKm2: 2,
    flag: "🇲🇨",
  },
  {
    code: "ME",
    code3: "MNE",
    name: "Montenegro",
    officialName: "Montenegro",
    alternateNames: ["Crna Gora"],
    capital: "Podgorica",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 42.7087,
    lng: 19.3744,
    population: 620000,
    areaKm2: 13812,
    flag: "🇲🇪",
  },
  {
    code: "NL",
    code3: "NLD",
    name: "Netherlands",
    officialName: "Kingdom of the Netherlands",
    alternateNames: ["Holland", "The Netherlands"],
    capital: "Amsterdam",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 52.1326,
    lng: 5.2913,
    population: 17500000,
    areaKm2: 41543,
    flag: "🇳🇱",
  },
  {
    code: "MK",
    code3: "MKD",
    name: "North Macedonia",
    officialName: "Republic of North Macedonia",
    alternateNames: ["Macedonia", "FYROM"],
    capital: "Skopje",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 41.5124,
    lng: 21.7453,
    population: 2100000,
    areaKm2: 25713,
    flag: "🇲🇰",
  },
  {
    code: "NO",
    code3: "NOR",
    name: "Norway",
    officialName: "Kingdom of Norway",
    alternateNames: ["Norge"],
    capital: "Oslo",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 60.472,
    lng: 8.4689,
    population: 5400000,
    areaKm2: 323802,
    flag: "🇳🇴",
  },
  {
    code: "PL",
    code3: "POL",
    name: "Poland",
    officialName: "Republic of Poland",
    alternateNames: ["Polska"],
    capital: "Warsaw",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 51.9194,
    lng: 19.1451,
    population: 38200000,
    areaKm2: 312696,
    flag: "🇵🇱",
  },
  {
    code: "PT",
    code3: "PRT",
    name: "Portugal",
    officialName: "Portuguese Republic",
    alternateNames: [],
    capital: "Lisbon",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 39.3999,
    lng: -8.2245,
    population: 10300000,
    areaKm2: 92212,
    flag: "🇵🇹",
  },
  {
    code: "RO",
    code3: "ROU",
    name: "Romania",
    officialName: "Romania",
    alternateNames: ["România"],
    capital: "Bucharest",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 45.9432,
    lng: 24.9668,
    population: 19200000,
    areaKm2: 238391,
    flag: "🇷🇴",
  },
  {
    code: "RU",
    code3: "RUS",
    name: "Russia",
    officialName: "Russian Federation",
    alternateNames: ["Russian Federation", "Rossiya"],
    capital: "Moscow",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 61.524,
    lng: 105.3188,
    population: 144100000,
    areaKm2: 17098242,
    flag: "🇷🇺",
  },
  {
    code: "SM",
    code3: "SMR",
    name: "San Marino",
    officialName: "Republic of San Marino",
    alternateNames: [],
    capital: "San Marino",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 43.9424,
    lng: 12.4578,
    population: 34000,
    areaKm2: 61,
    flag: "🇸🇲",
  },
  {
    code: "RS",
    code3: "SRB",
    name: "Serbia",
    officialName: "Republic of Serbia",
    alternateNames: ["Srbija"],
    capital: "Belgrade",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 44.0165,
    lng: 21.0059,
    population: 6800000,
    areaKm2: 88361,
    flag: "🇷🇸",
  },
  {
    code: "SK",
    code3: "SVK",
    name: "Slovakia",
    officialName: "Slovak Republic",
    alternateNames: ["Slovensko"],
    capital: "Bratislava",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 48.669,
    lng: 19.699,
    population: 5500000,
    areaKm2: 49037,
    flag: "🇸🇰",
  },
  {
    code: "SI",
    code3: "SVN",
    name: "Slovenia",
    officialName: "Republic of Slovenia",
    alternateNames: ["Slovenija"],
    capital: "Ljubljana",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 46.1512,
    lng: 14.9955,
    population: 2100000,
    areaKm2: 20273,
    flag: "🇸🇮",
  },
  {
    code: "ES",
    code3: "ESP",
    name: "Spain",
    officialName: "Kingdom of Spain",
    alternateNames: ["España", "Espana"],
    capital: "Madrid",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 40.4637,
    lng: -3.7492,
    population: 47400000,
    areaKm2: 505992,
    flag: "🇪🇸",
  },
  {
    code: "SE",
    code3: "SWE",
    name: "Sweden",
    officialName: "Kingdom of Sweden",
    alternateNames: ["Sverige"],
    capital: "Stockholm",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 60.1282,
    lng: 18.6435,
    population: 10400000,
    areaKm2: 450295,
    flag: "🇸🇪",
  },
  {
    code: "CH",
    code3: "CHE",
    name: "Switzerland",
    officialName: "Swiss Confederation",
    alternateNames: ["Schweiz", "Suisse", "Svizzera"],
    capital: "Bern",
    continent: "Europe",
    subregion: "Western Europe",
    lat: 46.8182,
    lng: 8.2275,
    population: 8800000,
    areaKm2: 41285,
    flag: "🇨🇭",
  },
  {
    code: "UA",
    code3: "UKR",
    name: "Ukraine",
    officialName: "Ukraine",
    alternateNames: [],
    capital: "Kyiv",
    continent: "Europe",
    subregion: "Eastern Europe",
    lat: 48.3794,
    lng: 31.1656,
    population: 44100000,
    areaKm2: 603500,
    flag: "🇺🇦",
  },
  {
    code: "GB",
    code3: "GBR",
    name: "United Kingdom",
    officialName: "United Kingdom of Great Britain and Northern Ireland",
    alternateNames: ["UK", "Britain", "Great Britain", "England"],
    capital: "London",
    continent: "Europe",
    subregion: "Northern Europe",
    lat: 55.3781,
    lng: -3.436,
    population: 67500000,
    areaKm2: 242495,
    flag: "🇬🇧",
  },
  {
    code: "VA",
    code3: "VAT",
    name: "Vatican City",
    officialName: "Vatican City State",
    alternateNames: ["Holy See", "The Vatican"],
    capital: "Vatican City",
    continent: "Europe",
    subregion: "Southern Europe",
    lat: 41.9029,
    lng: 12.4534,
    population: 800,
    areaKm2: 0.44,
    flag: "🇻🇦",
  },

  // ============ NORTH AMERICA ============
  {
    code: "AG",
    code3: "ATG",
    name: "Antigua and Barbuda",
    officialName: "Antigua and Barbuda",
    alternateNames: ["Antigua"],
    capital: "St. John's",
    continent: "North America",
    subregion: "Caribbean",
    lat: 17.0608,
    lng: -61.7964,
    population: 100000,
    areaKm2: 443,
    flag: "🇦🇬",
  },
  {
    code: "BS",
    code3: "BHS",
    name: "Bahamas",
    officialName: "Commonwealth of The Bahamas",
    alternateNames: ["The Bahamas"],
    capital: "Nassau",
    continent: "North America",
    subregion: "Caribbean",
    lat: 25.0343,
    lng: -77.3963,
    population: 400000,
    areaKm2: 13943,
    flag: "🇧🇸",
  },
  {
    code: "BB",
    code3: "BRB",
    name: "Barbados",
    officialName: "Barbados",
    alternateNames: [],
    capital: "Bridgetown",
    continent: "North America",
    subregion: "Caribbean",
    lat: 13.1939,
    lng: -59.5432,
    population: 290000,
    areaKm2: 430,
    flag: "🇧🇧",
  },
  {
    code: "BZ",
    code3: "BLZ",
    name: "Belize",
    officialName: "Belize",
    alternateNames: ["British Honduras"],
    capital: "Belmopan",
    continent: "North America",
    subregion: "Central America",
    lat: 17.1899,
    lng: -88.4976,
    population: 420000,
    areaKm2: 22966,
    flag: "🇧🇿",
  },
  {
    code: "CA",
    code3: "CAN",
    name: "Canada",
    officialName: "Canada",
    alternateNames: [],
    capital: "Ottawa",
    continent: "North America",
    subregion: "Northern America",
    lat: 56.1304,
    lng: -106.3468,
    population: 38900000,
    areaKm2: 9984670,
    flag: "🇨🇦",
  },
  {
    code: "CR",
    code3: "CRI",
    name: "Costa Rica",
    officialName: "Republic of Costa Rica",
    alternateNames: [],
    capital: "San José",
    continent: "North America",
    subregion: "Central America",
    lat: 9.7489,
    lng: -83.7534,
    population: 5200000,
    areaKm2: 51100,
    flag: "🇨🇷",
  },
  {
    code: "CU",
    code3: "CUB",
    name: "Cuba",
    officialName: "Republic of Cuba",
    alternateNames: [],
    capital: "Havana",
    continent: "North America",
    subregion: "Caribbean",
    lat: 21.5218,
    lng: -77.7812,
    population: 11300000,
    areaKm2: 109884,
    flag: "🇨🇺",
  },
  {
    code: "DM",
    code3: "DMA",
    name: "Dominica",
    officialName: "Commonwealth of Dominica",
    alternateNames: [],
    capital: "Roseau",
    continent: "North America",
    subregion: "Caribbean",
    lat: 15.415,
    lng: -61.371,
    population: 72000,
    areaKm2: 751,
    flag: "🇩🇲",
  },
  {
    code: "DO",
    code3: "DOM",
    name: "Dominican Republic",
    officialName: "Dominican Republic",
    alternateNames: [],
    capital: "Santo Domingo",
    continent: "North America",
    subregion: "Caribbean",
    lat: 18.7357,
    lng: -70.1627,
    population: 11100000,
    areaKm2: 48671,
    flag: "🇩🇴",
  },
  {
    code: "SV",
    code3: "SLV",
    name: "El Salvador",
    officialName: "Republic of El Salvador",
    alternateNames: [],
    capital: "San Salvador",
    continent: "North America",
    subregion: "Central America",
    lat: 13.7942,
    lng: -88.8965,
    population: 6500000,
    areaKm2: 21041,
    flag: "🇸🇻",
  },
  {
    code: "GD",
    code3: "GRD",
    name: "Grenada",
    officialName: "Grenada",
    alternateNames: [],
    capital: "St. George's",
    continent: "North America",
    subregion: "Caribbean",
    lat: 12.1165,
    lng: -61.679,
    population: 113000,
    areaKm2: 344,
    flag: "🇬🇩",
  },
  {
    code: "GT",
    code3: "GTM",
    name: "Guatemala",
    officialName: "Republic of Guatemala",
    alternateNames: [],
    capital: "Guatemala City",
    continent: "North America",
    subregion: "Central America",
    lat: 15.7835,
    lng: -90.2308,
    population: 17600000,
    areaKm2: 108889,
    flag: "🇬🇹",
  },
  {
    code: "HT",
    code3: "HTI",
    name: "Haiti",
    officialName: "Republic of Haiti",
    alternateNames: [],
    capital: "Port-au-Prince",
    continent: "North America",
    subregion: "Caribbean",
    lat: 18.9712,
    lng: -72.2852,
    population: 11600000,
    areaKm2: 27750,
    flag: "🇭🇹",
  },
  {
    code: "HN",
    code3: "HND",
    name: "Honduras",
    officialName: "Republic of Honduras",
    alternateNames: [],
    capital: "Tegucigalpa",
    continent: "North America",
    subregion: "Central America",
    lat: 15.2,
    lng: -86.2419,
    population: 10300000,
    areaKm2: 112492,
    flag: "🇭🇳",
  },
  {
    code: "JM",
    code3: "JAM",
    name: "Jamaica",
    officialName: "Jamaica",
    alternateNames: [],
    capital: "Kingston",
    continent: "North America",
    subregion: "Caribbean",
    lat: 18.1096,
    lng: -77.2975,
    population: 3000000,
    areaKm2: 10991,
    flag: "🇯🇲",
  },
  {
    code: "MX",
    code3: "MEX",
    name: "Mexico",
    officialName: "United Mexican States",
    alternateNames: ["México"],
    capital: "Mexico City",
    continent: "North America",
    subregion: "Central America",
    lat: 23.6345,
    lng: -102.5528,
    population: 129200000,
    areaKm2: 1964375,
    flag: "🇲🇽",
  },
  {
    code: "NI",
    code3: "NIC",
    name: "Nicaragua",
    officialName: "Republic of Nicaragua",
    alternateNames: [],
    capital: "Managua",
    continent: "North America",
    subregion: "Central America",
    lat: 12.8654,
    lng: -85.2072,
    population: 6800000,
    areaKm2: 130373,
    flag: "🇳🇮",
  },
  {
    code: "PA",
    code3: "PAN",
    name: "Panama",
    officialName: "Republic of Panama",
    alternateNames: ["Panamá"],
    capital: "Panama City",
    continent: "North America",
    subregion: "Central America",
    lat: 8.538,
    lng: -80.7821,
    population: 4400000,
    areaKm2: 75417,
    flag: "🇵🇦",
  },
  {
    code: "KN",
    code3: "KNA",
    name: "Saint Kitts and Nevis",
    officialName: "Federation of Saint Christopher and Nevis",
    alternateNames: ["St. Kitts and Nevis", "St Kitts"],
    capital: "Basseterre",
    continent: "North America",
    subregion: "Caribbean",
    lat: 17.3578,
    lng: -62.783,
    population: 54000,
    areaKm2: 261,
    flag: "🇰🇳",
  },
  {
    code: "LC",
    code3: "LCA",
    name: "Saint Lucia",
    officialName: "Saint Lucia",
    alternateNames: ["St. Lucia"],
    capital: "Castries",
    continent: "North America",
    subregion: "Caribbean",
    lat: 13.9094,
    lng: -60.9789,
    population: 184000,
    areaKm2: 616,
    flag: "🇱🇨",
  },
  {
    code: "VC",
    code3: "VCT",
    name: "Saint Vincent and the Grenadines",
    officialName: "Saint Vincent and the Grenadines",
    alternateNames: ["St. Vincent", "SVG"],
    capital: "Kingstown",
    continent: "North America",
    subregion: "Caribbean",
    lat: 12.9843,
    lng: -61.2872,
    population: 111000,
    areaKm2: 389,
    flag: "🇻🇨",
  },
  {
    code: "TT",
    code3: "TTO",
    name: "Trinidad and Tobago",
    officialName: "Republic of Trinidad and Tobago",
    alternateNames: ["T&T"],
    capital: "Port of Spain",
    continent: "North America",
    subregion: "Caribbean",
    lat: 10.6918,
    lng: -61.2225,
    population: 1400000,
    areaKm2: 5131,
    flag: "🇹🇹",
  },
  {
    code: "US",
    code3: "USA",
    name: "United States",
    officialName: "United States of America",
    alternateNames: [
      "USA",
      "US",
      "America",
      "United States of America",
      "The States",
    ],
    capital: "Washington, D.C.",
    continent: "North America",
    subregion: "Northern America",
    lat: 37.0902,
    lng: -95.7129,
    population: 331900000,
    areaKm2: 9833520,
    flag: "🇺🇸",
  },

  // ============ SOUTH AMERICA ============
  {
    code: "AR",
    code3: "ARG",
    name: "Argentina",
    officialName: "Argentine Republic",
    alternateNames: [],
    capital: "Buenos Aires",
    continent: "South America",
    subregion: "South America",
    lat: -38.4161,
    lng: -63.6167,
    population: 46000000,
    areaKm2: 2780400,
    flag: "🇦🇷",
  },
  {
    code: "BO",
    code3: "BOL",
    name: "Bolivia",
    officialName: "Plurinational State of Bolivia",
    alternateNames: [],
    capital: "Sucre",
    continent: "South America",
    subregion: "South America",
    lat: -16.2902,
    lng: -63.5887,
    population: 12000000,
    areaKm2: 1098581,
    flag: "🇧🇴",
  },
  {
    code: "BR",
    code3: "BRA",
    name: "Brazil",
    officialName: "Federative Republic of Brazil",
    alternateNames: ["Brasil"],
    capital: "Brasília",
    continent: "South America",
    subregion: "South America",
    lat: -14.235,
    lng: -51.9253,
    population: 214300000,
    areaKm2: 8515767,
    flag: "🇧🇷",
  },
  {
    code: "CL",
    code3: "CHL",
    name: "Chile",
    officialName: "Republic of Chile",
    alternateNames: [],
    capital: "Santiago",
    continent: "South America",
    subregion: "South America",
    lat: -35.6751,
    lng: -71.543,
    population: 19500000,
    areaKm2: 756102,
    flag: "🇨🇱",
  },
  {
    code: "CO",
    code3: "COL",
    name: "Colombia",
    officialName: "Republic of Colombia",
    alternateNames: [],
    capital: "Bogotá",
    continent: "South America",
    subregion: "South America",
    lat: 4.5709,
    lng: -74.2973,
    population: 51900000,
    areaKm2: 1141748,
    flag: "🇨🇴",
  },
  {
    code: "EC",
    code3: "ECU",
    name: "Ecuador",
    officialName: "Republic of Ecuador",
    alternateNames: [],
    capital: "Quito",
    continent: "South America",
    subregion: "South America",
    lat: -1.8312,
    lng: -78.1834,
    population: 18000000,
    areaKm2: 283561,
    flag: "🇪🇨",
  },
  {
    code: "GY",
    code3: "GUY",
    name: "Guyana",
    officialName: "Co-operative Republic of Guyana",
    alternateNames: [],
    capital: "Georgetown",
    continent: "South America",
    subregion: "South America",
    lat: 4.8604,
    lng: -58.9302,
    population: 800000,
    areaKm2: 214969,
    flag: "🇬🇾",
  },
  {
    code: "PY",
    code3: "PRY",
    name: "Paraguay",
    officialName: "Republic of Paraguay",
    alternateNames: [],
    capital: "Asunción",
    continent: "South America",
    subregion: "South America",
    lat: -23.4425,
    lng: -58.4438,
    population: 7400000,
    areaKm2: 406752,
    flag: "🇵🇾",
  },
  {
    code: "PE",
    code3: "PER",
    name: "Peru",
    officialName: "Republic of Peru",
    alternateNames: ["Perú"],
    capital: "Lima",
    continent: "South America",
    subregion: "South America",
    lat: -9.19,
    lng: -75.0152,
    population: 33700000,
    areaKm2: 1285216,
    flag: "🇵🇪",
  },
  {
    code: "SR",
    code3: "SUR",
    name: "Suriname",
    officialName: "Republic of Suriname",
    alternateNames: [],
    capital: "Paramaribo",
    continent: "South America",
    subregion: "South America",
    lat: 3.9193,
    lng: -56.0278,
    population: 600000,
    areaKm2: 163820,
    flag: "🇸🇷",
  },
  {
    code: "UY",
    code3: "URY",
    name: "Uruguay",
    officialName: "Oriental Republic of Uruguay",
    alternateNames: [],
    capital: "Montevideo",
    continent: "South America",
    subregion: "South America",
    lat: -32.5228,
    lng: -55.7658,
    population: 3500000,
    areaKm2: 176215,
    flag: "🇺🇾",
  },
  {
    code: "VE",
    code3: "VEN",
    name: "Venezuela",
    officialName: "Bolivarian Republic of Venezuela",
    alternateNames: [],
    capital: "Caracas",
    continent: "South America",
    subregion: "South America",
    lat: 6.4238,
    lng: -66.5897,
    population: 28400000,
    areaKm2: 916445,
    flag: "🇻🇪",
  },

  // ============ OCEANIA ============
  {
    code: "AU",
    code3: "AUS",
    name: "Australia",
    officialName: "Commonwealth of Australia",
    alternateNames: ["Oz", "Down Under"],
    capital: "Canberra",
    continent: "Oceania",
    subregion: "Australia and New Zealand",
    lat: -25.2744,
    lng: 133.7751,
    population: 26000000,
    areaKm2: 7692024,
    flag: "🇦🇺",
  },
  {
    code: "FJ",
    code3: "FJI",
    name: "Fiji",
    officialName: "Republic of Fiji",
    alternateNames: [],
    capital: "Suva",
    continent: "Oceania",
    subregion: "Melanesia",
    lat: -17.7134,
    lng: 178.065,
    population: 900000,
    areaKm2: 18274,
    flag: "🇫🇯",
  },
  {
    code: "KI",
    code3: "KIR",
    name: "Kiribati",
    officialName: "Republic of Kiribati",
    alternateNames: [],
    capital: "South Tarawa",
    continent: "Oceania",
    subregion: "Micronesia",
    lat: 1.8709,
    lng: -157.3626,
    population: 120000,
    areaKm2: 811,
    flag: "🇰🇮",
  },
  {
    code: "MH",
    code3: "MHL",
    name: "Marshall Islands",
    officialName: "Republic of the Marshall Islands",
    alternateNames: [],
    capital: "Majuro",
    continent: "Oceania",
    subregion: "Micronesia",
    lat: 7.1315,
    lng: 171.1845,
    population: 60000,
    areaKm2: 181,
    flag: "🇲🇭",
  },
  {
    code: "FM",
    code3: "FSM",
    name: "Micronesia",
    officialName: "Federated States of Micronesia",
    alternateNames: ["FSM", "Federated States of Micronesia"],
    capital: "Palikir",
    continent: "Oceania",
    subregion: "Micronesia",
    lat: 7.4256,
    lng: 150.5508,
    population: 115000,
    areaKm2: 702,
    flag: "🇫🇲",
  },
  {
    code: "NR",
    code3: "NRU",
    name: "Nauru",
    officialName: "Republic of Nauru",
    alternateNames: [],
    capital: "Yaren",
    continent: "Oceania",
    subregion: "Micronesia",
    lat: -0.5228,
    lng: 166.9315,
    population: 11000,
    areaKm2: 21,
    flag: "🇳🇷",
  },
  {
    code: "NZ",
    code3: "NZL",
    name: "New Zealand",
    officialName: "New Zealand",
    alternateNames: ["Aotearoa", "NZ"],
    capital: "Wellington",
    continent: "Oceania",
    subregion: "Australia and New Zealand",
    lat: -40.9006,
    lng: 174.886,
    population: 5100000,
    areaKm2: 270467,
    flag: "🇳🇿",
  },
  {
    code: "PW",
    code3: "PLW",
    name: "Palau",
    officialName: "Republic of Palau",
    alternateNames: [],
    capital: "Ngerulmud",
    continent: "Oceania",
    subregion: "Micronesia",
    lat: 7.515,
    lng: 134.5825,
    population: 18000,
    areaKm2: 459,
    flag: "🇵🇼",
  },
  {
    code: "PG",
    code3: "PNG",
    name: "Papua New Guinea",
    officialName: "Independent State of Papua New Guinea",
    alternateNames: ["PNG"],
    capital: "Port Moresby",
    continent: "Oceania",
    subregion: "Melanesia",
    lat: -6.315,
    lng: 143.9555,
    population: 10100000,
    areaKm2: 462840,
    flag: "🇵🇬",
  },
  {
    code: "WS",
    code3: "WSM",
    name: "Samoa",
    officialName: "Independent State of Samoa",
    alternateNames: ["Western Samoa"],
    capital: "Apia",
    continent: "Oceania",
    subregion: "Polynesia",
    lat: -13.759,
    lng: -172.1046,
    population: 200000,
    areaKm2: 2842,
    flag: "🇼🇸",
  },
  {
    code: "SB",
    code3: "SLB",
    name: "Solomon Islands",
    officialName: "Solomon Islands",
    alternateNames: [],
    capital: "Honiara",
    continent: "Oceania",
    subregion: "Melanesia",
    lat: -9.6457,
    lng: 160.1562,
    population: 700000,
    areaKm2: 28896,
    flag: "🇸🇧",
  },
  {
    code: "TO",
    code3: "TON",
    name: "Tonga",
    officialName: "Kingdom of Tonga",
    alternateNames: [],
    capital: "Nukuʻalofa",
    continent: "Oceania",
    subregion: "Polynesia",
    lat: -21.179,
    lng: -175.1982,
    population: 106000,
    areaKm2: 747,
    flag: "🇹🇴",
  },
  {
    code: "TV",
    code3: "TUV",
    name: "Tuvalu",
    officialName: "Tuvalu",
    alternateNames: [],
    capital: "Funafuti",
    continent: "Oceania",
    subregion: "Polynesia",
    lat: -7.1095,
    lng: 177.6493,
    population: 12000,
    areaKm2: 26,
    flag: "🇹🇻",
  },
  {
    code: "VU",
    code3: "VUT",
    name: "Vanuatu",
    officialName: "Republic of Vanuatu",
    alternateNames: [],
    capital: "Port Vila",
    continent: "Oceania",
    subregion: "Melanesia",
    lat: -15.3767,
    lng: 166.9592,
    population: 320000,
    areaKm2: 12189,
    flag: "🇻🇺",
  },
];

/**
 * Lookup a country by its ISO alpha-2 code.
 */
export function getCountryByCode(code: string): Country | undefined {
  const upper = code.toUpperCase();
  return countries.find((c) => c.code === upper);
}

/**
 * Lookup a country by name (case-insensitive). Checks `name`, `officialName`,
 * and every entry in `alternateNames`.
 */
export function getCountryByName(name: string): Country | undefined {
  const lower = name.toLowerCase();
  return countries.find(
    (c) =>
      c.name.toLowerCase() === lower ||
      c.officialName?.toLowerCase() === lower ||
      c.alternateNames.some((alt) => alt.toLowerCase() === lower),
  );
}

/**
 * Flat array of all ISO alpha-2 country codes.
 */
export const countryCodes: string[] = countries.map((c) => c.code);
